plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.worldmap'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.worldmap'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-maps:20.0.0'
}
